name: Alembic Migrations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'app/models/**'
      - 'alembic.ini'
      - 'alembic/**'
      - 'pyproject.toml'
      - 'uv.lock'
  workflow_call:
    inputs:
      postgres_user:
        required: true
        type: string
      postgres_password:
        required: true
        type: string
      postgres_db:
        required: true
        type: string

jobs:
  alembic-migrations:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://${{ inputs.postgres_user }}:${{ inputs.postgres_password }}@db:5432/${{ inputs.postgres_db }}
      PROJECT_NAME: dev-thedataproxy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: |
          docker build -t ${PROJECT_NAME}-backend:latest ./backend

      - name: Debug inputs and prepare Alembic configuration
        run: |
          docker run --rm \
            -v /home/runner/work/platform-thedataproxy.com/platform-thedataproxy.com:/app \
            ${PROJECT_NAME}-backend:latest \
            bash -c "echo 'Debug: POSTGRES_USER=${{ inputs.postgres_user }}' && \
                     echo 'Debug: POSTGRES_PASSWORD=${{ inputs.postgres_password }}' && \
                     echo 'Debug: POSTGRES_DB=${{ inputs.postgres_db }}' && \
                     printf '[alembic]\nscript_location = app/alembic\nsqlalchemy.url = ${DATABASE_URL}\n' > /app/alembic.ini && \
                     mkdir -p /app/app/alembic/versions && \
                     echo 'import os\nfrom alembic import context\nfrom app.models import SQLModel\nfrom app.core.config import settings\ntarget_metadata = SQLModel.metadata\ndef get_url():\n    return str(settings.SQLALCHEMY_DATABASE_URI)\nif context.is_offline_mode():\n    url = get_url()\n    context.configure(url=url, target_metadata=target_metadata, literal_binds=True, compare_type=True)\n    with context.begin_transaction():\n        context.run_migrations()' > /app/app/alembic/env.py && \
                     echo 'Listing /app contents:' && ls -la /app && \
                     echo 'Listing /app/app/alembic contents:' && ls -la /app/app/alembic && \
                     echo 'Content of alembic.ini:' && cat /app/alembic.ini"

      - name: Run migrations in container
        run: |
          docker run --rm \
            -e SQLALCHEMY_URL="${DATABASE_URL}" \
            -v /home/runner/work/platform-thedataproxy.com/platform-thedataproxy.com:/app \
            ${PROJECT_NAME}-backend:latest \
            bash -c "if ! command -v alembic >/dev/null 2>&1; then pip install alembic; fi && \
                     cat /app/alembic.ini && \
                     alembic revision --autogenerate -m 'Auto-generated migration for model changes'"

      - name: Check for uncommitted migrations
        id: check_migrations
        run: |
          if git diff --name-only | grep '^app/alembic/versions/'; then
            echo "New migration files detected"
            echo "has_migrations=true" >> $GITHUB_OUTPUT
          else
            echo "No new migration files"
            echo "has_migrations=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit new migration files
        if: steps.check_migrations.outputs.has_migrations == 'true' && github.event_name == 'push'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add app/alembic/versions/*
          git commit -m "Add auto-generated Alembic migration"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}